# Generated by Django 5.1 on 2024-08-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
